### ISSUE TITLE
Make project ready for packaging

### ISSUE THREAD

**Issue by SpotlightKid** [jpcima/rc-effect-playground#4]
## Task description

This is a umbrella issue for tasks to carry out to make plugin release ready.

## To do

* [ ] Rename repository, add description, URL and keywords
* [ ] Remove prototype files from repo (maybe keep them in a branch)
* [ ] Write [README](./README.md) #9
* [ ] Add [AUTHORS](./AUTHORS.md) file
* [ ] Add [CHANGELOG](./CHANGELOG.md) file
* [ ] Ensure all meta-data is present
* [ ] Add CI files
* [ ] Create landing page at [plugin URI](http://jpcima.sdf1.org/lv2/hera-chorus) (or with redirect to github.io)
* [ ] Create screenshot(s) and add it/them to landing page
* [ ] Create sound demo(s) and add it/them to landing page
* [ ] Add `.desktop` file and menu icon

## Further information

See also: https://github.com/NixOS/nixpkgs/pull/74038

**Comment by jpcima** [comment]
Hi, I think about these items as a roadmap to a final product.

- Create the clean repository
- To fill in the metadata as needed, project page, authorship, contact, etc., decide a license.
- Possibly, point the plugin URL to a Github Pages site. It can host a presentation, some sound, etc.

Technical
- To finalize the set of parameters and their adjustment, as you find adequate. Remove the unnecessary.
- To remake Juno-Simple and Juno-Advanced into one plugin. J60/JX3p/JX03 as presets.
- (can wait next release)To create a user interface. It will be nice to prototype the UX first, and implement. In my point of view, not doubt the worst time-consuming task.
- install the automation of build and deployment (I've already done, just copy-paste)
- (optional)a MOD GUI

Publishing
- Post previews to KVR, Linuxaudio and other channels, collect feedback

[...]

**Comment by magnetophon** [comment]
Any news on this?

**Comment by SpotlightKid** [comment]
Not really, sorry. I got hung up on other projects and TBH, the plugins work for me as is, since I usually use the generic UI anyway.

I'll give it another shot soon, I hope.

**Comment by magnetophon** [comment]
It works for me as is as well, but someone told me to hold off packaging it for NixOS because you where not ready yet.

I suggest to just do the minimum needed to make it "ready for packaging".
